#!/usr/bin/perl -w

print "# generated by intfun.pl - do not edit\n";
print "# handlers\n";
print ".globl dotsame\n";
for(my $i = 0; $i < 256; $i++){
    print ".globl intr$i\n";
    print "intr$i:\n";
    if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
        print "  pushl \$0\n";
    }
    print "  pushl \$$i\n";
    print "  jmp dotsame\n";
}

print "\n# intr table\n";
print ".data\n";
print ".globl intrs\n";
print "intrs:\n";
for(my $i = 0; $i < 256; $i++){
    print "  .long intr$i\n";
}
